### ISSUE TITLE
qsrs from PyPi crashes on Linux on some CPUs

### ISSUE THREAD

**Issue by WolfLink** [BQSKit/qsearch#12]
qsrs, the Rust implementation of parts of Qsearch, is currently not working properly on certain CPUs running Linux, when installed from PyPi.

Workaround: Build qsrs yourself.  See https://github.com/BQSKit/qsearch/blob/master/qsrs/README.md for more information.
Workaround: Uninstall qsrs and Qsearch will fallback to the Python imlementations.  Note that this will result in slow runtimes.

**Comment by ethanhs** [comment]
Notably, I think this only affects machines where AVX is not available, which is not true of most hardware made in the last 5 years.
