### ISSUE TITLE
Install fails on MacOS due to failing ceres dependency

### ISSUE THREAD

**Issue by rsln-s** [BQSKit/qsearch#26]
Doing the following fails:

```
% pip install qsearch
% cd qsearch/examples
% python qiskit_import.py  
Traceback (most recent call last):
  File "qiskit_import.py", line 3, in <module>
    from qsearch import multistart_solvers, utils, Options, defaults, unitaries
  File "/Users/ruslan/soft/anaconda3/envs/qiskit_latest/lib/python3.8/site-packages/qsearch/multistart_solvers.py", line 9, in <module>
    from qsrs import native_from_object
ImportError: dlopen(/Users/ruslan/soft/anaconda3/envs/qiskit_latest/lib/python3.8/site-packages/qsrs.cpython-38-darwin.so, 2): Library not loaded: /usr/local/opt/ceres-solver/lib/libceres.1.dylib
  Referenced from: /Users/ruslan/soft/anaconda3/envs/qiskit_latest/lib/python3.8/site-packages/qsrs.cpython-38-darwin.so
  Reason: image not found
 ```

My best guess is due to `ceres-solver` not being specified as a dependency. Now, installing it does not solve the problem either, as the version of `ceres` in homebrew is different:

```
 % ls /usr/local/opt/ceres-solver/lib/
cmake/                libceres.2.0.0.dylib  libceres.2.dylib@     libceres.dylib@
```

In other words, the package is looking for `libceres.1.dylib`, but getting `libceres.2.dylib`, which is different. Symlinking between the two does not work (qsrs is expecting different symbols).

Installing qsearch from source (`pip install -U -e .`) also fails, as qsrs is not installed from source.

**Comment by ethanhs** [comment]
Hi, I have changes to fix this in the `dev` branch, I will try to release them today or tomorrow.

**Comment by rsln-s** [comment]
Strange, did I try installing from source in the `dev` branch. Would using these require installing qsrs from source (that part I couldn't get to work)?

**Comment by ethanhs** [comment]
@rsln-s the new wheels should be up now. If you run `python3 -m pip install -U qsrs` you should get the latest version. You may or may not need to update your pip for this to work.

**Comment by rsln-s** [comment]
@ethanhs thank you, that has resolved the issue. 
I would suggest adding `ceres-solver` as a dependency in the README for qsearch as `pip3 install qsearch` does not install it. On macOS `brew install ceres-solver` works great, as specified in README for qsrs.
