### ISSUE TITLE
qsearch, QFast and synthesizing 5 qubit Clifford unitaries

### ISSUE THREAD

**Issue by rsln-s** [BQSKit/qsearch#27]
I am trying to synthesize circuits with low CNOT count for a particular IBM Q backend implementing Clifford unitaries that look not too dissimilar from stabilizer parity checks. I understand neither qsearch nor QFast takes advantage of the structure of Clifford group, but I mention it anyway for context. I am using [qft5_ibm_yorktown.py](https://github.com/BQSKit/qsearch/blob/master/examples/qft5_ibm_yorktown.py) example as a starting point. The problem I'm observing is that qsearch on the five-qubit unitary below does not converge even after 2+ days of runtime. 

My questions are then:

- What is the expected runtime of qsearch on 5 qubit unitaries?
- Is there a way to trade off runtime and quality of solution in qsearch?
- Can QFast (which seems to exhibit better scaling, based on the paper) be used to synthesize circuits for particular hardware connectivity?

Here are the code and the example circuit to reproduce the high runtime:
```python
import glob
from pathlib import Path
import uuid
import qiskit
from qiskit.quantum_info import Statevector

from qsearch import (
    gates, unitaries, Project,
    leap_compiler, post_processing,
    parallelizers, multistart_solvers,
    gatesets, assemblers, utils
)

def unitary_from_circuit(qc):
    backend = qiskit.BasicAer.get_backend('unitary_simulator')
    job = qiskit.execute(qc, backend)
    U = job.result().get_unitary()
    BE = utils.endian_reverse(U)
    return BE


if __name__ == '__main__':
    for fname in glob.glob('test.qasm'):
        qc = qiskit.QuantumCircuit.from_qasm_file(fname)
        print(qc.draw())
        # generate a unitary from the Qiskit circuit
        U1 = unitary_from_circuit(qc)

        circ_name = Path(fname).stem
        proj_name = 'ibmq-casablanca-' + Path(fname).stem + '-' + str(uuid.uuid4().hex)

        with Project(proj_name) as project:
                project.add_compilation(circ_name, U1)
                project["compiler_class"] = leap_compiler.LeapCompiler
                project["min_depth"] = 3
                project["gateset"] = gatesets.QubitCNOTAdjacencyList([[1,0], [1,2], [3,1], [5,3], [5,4], [6,5]])
                project["verbosity"] = 2
                project.run()
                print('Done running')
                project.post_process(post_processing.LEAPReoptimizing_PostProcessor(), solver=multistart_solvers.MultiStart_Solver(24), parallelizer=parallelizers.ProcessPoolParallelizer, weight_limit=5)
                print('Done post processing')
                qasm = project.assemble(circ_name, assembler=assemblers.ASSEMBLER_IBMOPENQASM)
                print('Done assembling')

        qc2 = qiskit.QuantumCircuit.from_qasm_str(qasm)
        print(qc2.draw())
        ok = Statevector.from_instruction(qc).equiv(Statevector.from_instruction(qc2))
        assert(ok)
        print(f"Old circuit CNOT count: {qc.decompose().decompose().num_nonlocal_gates()}, new circuit CNOT count: {qc2.num_nonlocal_gates()}, OK: {ok}")
```

Example circuit:
```
OPENQASM 2.0;
include "qelib1.inc";
qreg q0[5];
swap q0[4],q0[1];
h q0[1];
cx q0[1],q0[0];
cx q0[1],q0[2];
cx q0[1],q0[4];
swap q0[2],q0[3];
cx q0[1],q0[2];
h q0[1];
```

Qsearch log: 
[qsearch_log.txt](https://github.com/BQSKit/qsearch/files/6406694/qsearch_log.txt)

**Comment by WolfLink** [comment]
Qsearch does not perform mapping of logical qubits to physical qubits.  Instead, it will take the first n qubits as the logical qubits, and ignore the rest.  It will assume that the topology forms a connected graph between the logical qubits

In your script, the specified topology contains 7 qubits, but you are synthesizing a 5 qubit unitary, so only the first 5 qubits (qubits 0-4) are used, while the last two qubits (5 and 6) are ignored.  Under these conditions, the effective topology becomes [[1,0], [1,2], [3,1]], such that qubits 0-3 are connected but qubit 4 has no connections to other qubits.  This disconnected topology is unable to represent your unitary, so qsearch never converges.


I tried running your script with the following modified topology:

`project["gateset"] = gatesets.QubitCNOTAdjacencyList([[1,0], [1,2], [3,1], [4,3], [4,5], [6,4]])`

This topology has the same shape, but a different logical-physical mapping (what was previously logical qubit 4 is now logical qubit 5, and visa versa).  This topology is connected among the first 5 qubits, and the script produced a 13 CNOT circuit in under 10 minutes.  This is longer than the original circuit, but is much better than what you would get from adding SWAPs to the original circuit to map to this topology.



I noticed that the condition that you assert at the end:

`ok = Statevector.from_instruction(qc).equiv(Statevector.from_instruction(qc2))`

Compares only the state produced from applying these circuits to the zero state.  If this state is all that matters, such that you are not concerned with what the circuit does to other states, you can get better results by using the stateprep feature of our code.  I made the following changes:

```
# in the imports
from qsearch import defaults
```

```
# instead of U1 = unitary_from_circuit(qc)
s1 = utils.endian_reverse(np.array(Statevector.from_instruction(qc), dtype='complex128'))
```

```
# instead of project.add_compilation(circ_name, U1)
project.set_smart_defaults(defaults.stateprep_smart_defaults)
project.add_compilation(circ_name, np.eye(2**5, dtype='complex128'), target_state=s1)
```


Using stateprep, qsearch finished in under a minute with a 4 CNOT circuit.  This circuit produces the same state as the original circuit when applied to the zero state (the ok check succeeds) but will behave differently when applied to other initial states.

**Comment by rsln-s** [comment]
@WolfLink thank you for the prompt and very detailed response! Adjusting the topology fixed the problem. 
And thank you for pointing out that my assert at the end of the script does not actually check what I want it to check :) I should check that the two unitaries are equivalent.
