### ISSUE TITLE
Updated ZXZXZ and XZXZ gates on dev sometimes prevent the threshold of 10^-10 from being hit.

### ISSUE THREAD

**Issue by WolfLink** [BQSKit/qsearch#28]
The threshold of 10^-10 is sometimes not being hit after the change of X gates from Rx(pi/2) to sqrt(X) (as defined by IBM).

The round-trip test passes, and the gradient test passes, so it is does not seem like any computations are actually incorrect.  Perhaps the gradients are flatter with this new change, causing the optimizers to hit gradient-based convergence conditions earlier?

This issue must be investigated and solved before dev can be merged into master for the next release.

**Comment by ethanhs** [comment]
Fixed in db0590c1db74b3a64a3b9dbe717ec0e27833bc1a
