### ISSUE TITLE
QasmError when convert qasm to qiskit circuit

### ISSUE THREAD

**Issue by 4KColo** [BQSKit/qsearch#30]
Hi, I tried to convert a simple unitary into quantum circuit via qsearch. But I got an error message: 

raise QasmError("Expected an ID, received '" + str(program[1].value) + "'")
qiskit.qasm.exceptions.QasmError: "Expected an ID, received '='"

Can you tell me how to fix this error? Thank you in advance. Here is my code:

import numpy as np
import qsearch
import scipy.sparse.linalg as ssl
import qiskit
​
h = np.zeros([4,4], dtype='complex')
h[0,0] = 1.0
Uh = ssl.expm(-1j*h)
Uh_big_endian = qsearch.utils.endian_reverse(Uh)
​
project_dir = '/test/qsearch'
myproject = qsearch.Project(project_dir)
gate_name = 'Uh'
myproject.add_compilation(gate_name, Uh_big_endian)
myproject.run()
qasm = myproject.assemble('Uh')
    
qiskit.QuantumCircuit.from_qasm_str(qasm)

**Comment by WolfLink** [comment]
Firstly I'd like to let you know that Qsearch is no longer being actively maintained. You may want to check out BQSKit (https://github.com/BQSKit/bqskit) which includes the main synthesis technique that Qsearch implements as well as some other synthesis techniques and newer features.


That being said, the issue you are encountering is that by default `myproject.assemble("Uh")` actually outputs Qiskit Python code by default. You could use it in a script like this:

```
from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister
qiskit_code = myproject.assemble('Uh')
exec(qiskit_code)
myqiskitcircuit = qc
```


Alternatively, you can tell `assemble` to use the `IBMOPENQASM` assembler, which outputs qasm code that you can use in the `qiskit.QuantumCircuit.from_qasm_str` function.

```
qasm = myproject.assemble('Uh', assembler=qsearch.assemblers.ASSEMBLER_IBMOPENQASM)
myqiskitcircuit = qiskit.QuantumCircuit.from_qasm_str(qasm)
```
